### ISSUE TITLE
Code snippets on web post are centre aligned

### ISSUE THREAD

**Issue by pentaphobe** [SimonDanisch/julia-challenge#2]
Mayne not where to raise this, but I was reading with great interest until I reached the centred snippets.

Imagine I'm not alone :)

**Comment by SimonDanisch** [comment]
Thanks for the feedback :) What would you actually prefer?

**Comment by oxinabox** [comment]
They are left-aligned for me,
See below

![image](https://user-images.githubusercontent.com/5127634/45480306-487fde00-b77b-11e8-9f99-33856b8c63e0.png)

What are you seeing?

**Comment by pentaphobe** [comment]
Sorry for the slow response!

Super weird, I'm still seeing it [at this page](https://nextjournal.com/sdanisch/the-julia-challenge) maybe something weird on my end:

![image](https://user-images.githubusercontent.com/418523/45876135-1f93c480-bddd-11e8-81e4-4e53682ef67a.png)

If I'm alone, may as well close this. Sorry for wasting peoples' time!

**Comment by oxinabox** [comment]
That is honestly, amazing.
I can't replicate that even if I try hacking the CSS (I didn't try hard, though)

You should probably raise this with NextJournal support.

**Comment by SimonDanisch** [comment]
Do you have some browser plugin installed that messes with the CSS?

**Comment by pentaphobe** [comment]
@SimonDanisch this was my first though too (I've used some in the past) but couldn't identify one.

Interestingly, it didn't happen in incognito - so there's some kind of clash happening, but either way - obviously to do with my setup

_fights the urge to stay up late finding the origin_
